name: regrow
description: ReGrow - Food Rescue Prototype
publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^7.0.0
  flutter_map_location_marker: ^9.0.0
  flutter_map_marker_cluster: ^1.4.0
  latlong2: ^0.9.0

  provider: ^6.0.5
  image_picker: ^0.8.7+4
  uuid: ^3.0.7
  intl: ^0.18.0
  geolocator: ^12.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
